#' setup_tpm_files
#'
#' @param work_dir TAP output directory path
#' @param variable_map name of variables encoded in TAP output prefixes. Delimited by "_" and ".".
#'
#' @return data.table of files path to tpm files with metadata optionally extracted according to `variable_map`.
#' @export
#'
#' @examples
#' tap_out = "~/R_workspace.combined/TAPhelpR.data/honeybee_TAP_output"
#' tpm_files = setup_tpm_files(tap_out, variable_map = c("day", "sex", "rep"))
#' mat = load_matrix_from_tpm(tpm_files$file)
#' head(mat)
setup_tpm_files = function(work_dir, variable_map = NULL){
  files_dt = setup_files(work_dir, ".salmon_quant$", variable_map)
  files_dt$file = file.path(files_dt$file, "tpm.txt")
  stopifnot(file.exists(files_dt$file))
  files_dt
}


#' load_matrix_from_tpm
#'
#' @param files paths to tpm.txt files generated by TAP in the *salmon_quant directories.
#'
#' @return matrix of TPM values generated by salmon.
#' @export
#'
#' @examples
#' tap_out = "~/R_workspace.combined/TAPhelpR.data/honeybee_TAP_output"
#' tpm_files = setup_tpm_files(tap_out, variable_map = c("day", "sex", "rep"))
#' mat = load_matrix_from_tpm(tpm_files$file)
#' head(mat)
load_matrix_from_tpm = function(files){
  f_names = sub(".salmon_quant", "", basename(dirname(files)))
  names(files) = f_names
  tpm.l = suppressWarnings({
    lapply(files, fread, col.names = c("transcript_id", "tpm"))
  })
  tpm_dt = rbindlist(tpm.l, idcol = "name")
  tmp = dcast(tpm_dt, transcript_id~name, value.var = "tpm")
  mat = as.matrix(tmp[,-1])
  rownames(mat) = tmp$transcript_id
  mat
}

